use actix_web::Error;

#[actix_web::main]
async fn main () -> Result<(), Box<dyn std::io::Error>>{
    
}